/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge */

#ifndef _Included_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
#define _Included_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_script_reader
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1script_1reader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_card_reader
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1card_1reader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_message_handler
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1message_1handler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    create_duel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_create_1duel
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    start_duel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_start_1duel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    end_duel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_end_1duel
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_player_info
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1player_1info
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    get_log_message
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_get_1log_1message
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    get_message
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_get_1message
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    process
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_process
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    new_card
 * Signature: (IIBBBBB)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_new_1card
  (JNIEnv *, jclass, jint, jint, jbyte, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    new_tag_card
 * Signature: (IIBB)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_new_1tag_1card
  (JNIEnv *, jclass, jint, jint, jbyte, jbyte);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    query_card
 * Signature: (IBBBILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_query_1card
  (JNIEnv *, jclass, jint, jbyte, jbyte, jbyte, jint, jobject, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    query_field_count
 * Signature: (IBB)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_query_1field_1count
  (JNIEnv *, jclass, jint, jbyte, jbyte);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    query_field_card
 * Signature: (IBBILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_query_1field_1card
  (JNIEnv *, jclass, jint, jbyte, jbyte, jint, jobject, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    query_field_info
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_query_1field_1info
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_responsei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1responsei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    set_responseb
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_set_1responseb
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge
 * Method:    preload_script
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_cn_garymb_ygoserver_ygo_ocgwrapper_OcgcoreBridge_preload_1script
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
